"use client";

import Link from "next/link";
import { Eye, EyeOff, LockKeyhole, ShieldCheck } from "lucide-react";
import { useSearchParams, useRouter } from "next/navigation";
import { useState } from "react";
import { BrandLogo } from "@/components/brand-logo";
import { Button, Card, Input, Label } from "@/components/ui";
import { resetPassword } from "@/lib/api";
import { useAuthStore } from "@/store/auth-store";

export default function ResetPasswordForm() {
  const params = useSearchParams(); const router = useRouter(); const clearSession = useAuthStore((state) => state.clearSession); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event) { event.preventDefault(); setError(""); if (!params.get("token")) return setError("This reset link is invalid or expired."); if (password !== confirm) return setError("Passwords do not match."); setLoading(true); try { await resetPassword({ token: params.get("token"), password }); clearSession(); router.replace("/login?reset=success"); } catch (resetError) { setError(resetError.message); } finally { setLoading(false); } }
  return <main className="min-h-screen bg-background px-4 py-8 text-on-surface sm:px-6"><div className="mx-auto flex min-h-[calc(100vh-4rem)] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-outline-variant bg-surface shadow-xl"><header className="flex items-center justify-between border-b border-outline-variant px-6 py-5 sm:px-10"><Link href="/"><BrandLogo variant="light" className="w-36" priority /></Link><span className="text-xs font-semibold uppercase tracking-[0.16em] text-on-surface-variant">Account security</span></header><div className="grid flex-1 lg:grid-cols-[0.9fr_1.1fr]"><aside className="hidden bg-primary p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><ShieldCheck className="size-10" /><h1 className="mt-8 font-heading text-4xl font-semibold leading-tight">Choose a stronger password.</h1><p className="mt-5 max-w-sm text-sm leading-7 text-white/75">Use a password you have not used elsewhere to keep your ZoeLit account protected.</p></div><p className="text-xs text-white/60">Your reset link is valid for 15 minutes.</p></aside><section className="flex items-center p-6 sm:p-12"><Card className="w-full border-0 p-0 shadow-none"><div className="mb-8 grid size-12 place-items-center bg-primary/10 text-primary"><LockKeyhole className="size-5" /></div><h2 className="font-heading text-3xl font-semibold tracking-tight">Create a new password</h2><p className="mt-3 text-sm leading-6 text-on-surface-variant">Enter and confirm your new password below. Your previous password will stop working immediately.</p><form onSubmit={submit} className="mt-8 space-y-5"><div><Label>New password</Label><div className="relative mt-2"><Input className="pr-11" type={show ? "text" : "password"} autoComplete="new-password" required minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" onClick={() => setShow((value) => !value)} className="absolute right-3 top-1/2 -translate-y-1/2 text-on-surface-variant" aria-label={show ? "Hide password" : "Show password"}>{show ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div><p className="mt-2 text-xs text-on-surface-variant">At least 8 characters, including one uppercase letter and one number.</p></div><div><Label>Confirm password</Label><Input className="mt-2" type={show ? "text" : "password"} autoComplete="new-password" required value={confirm} onChange={(event) => setConfirm(event.target.value)} /></div>{error && <p className="text-sm text-error">{error}</p>}<Button className="w-full" disabled={loading}>{loading ? "Updating password..." : "Update password"}</Button></form><Link className="mt-8 inline-block text-sm font-semibold text-primary" href="/login">Back to sign in</Link></Card></section></div><footer className="border-t border-outline-variant px-6 py-4 text-center text-xs text-on-surface-variant sm:px-10">ZoeLit Commerce <span className="mx-2">|</span> Secure password recovery</footer></div></main>;
}
